title: Casburn Noronha
description: > # this means to ignore newlines until "baseurl:"
  This is my journey into the world of IT.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://github.com/casburn-noronha/casburn-noronha.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Casburn Noronha # add your name
author-img: cashu.jpg # add your photo
about-author: This is my journey into the world of IT. # add description
social-twitter: slaaysrcecoders # add your Twitter handle
social-facebook: casburn.noronha # add your Facebook handle
social-github: casburn-noronha # add your Github handle
social-linkedin: casburn-noronha # add your Linkedin handle
social-email: casburn.noronha # add your Email address

# Disqus
discus-identifier:https-casburn1988-github-io # add your discus identifier

# Tracker
analytics: 'UA-83999817-1' # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
